# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2a50f034922850246d8339126890a86f5646d063eae37dba13a82fae48e890e49bba3c11a00e6194823d603a129ccedb99f1c73dd6cc3a613cddabffc786055

test:
  secret_key_base: 89ffb6dc3fa9284c4792c0ba7dac3576675ec2910e22f5eaa13c48cd59b6fbe903dfd2c1745a4d8bbfe7d959e5af8ec6f2a81e49e834c6bd55b9d2d80a50b283

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
